name: Release
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Package source
        run: |
          mkdir -p dist
          git archive --format zip --output dist/cri-core-${{ github.ref_name }}.zip ${{ github.ref }}
      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/cri-core-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
