name: Release Dry Run
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Package source
        run: |
          mkdir -p dist
          git archive --format zip --output dist/cri-core-dryrun.zip HEAD
      - name: Upload artifact (dry run)
        uses: actions/upload-artifact@v4
        with:
          name: cri-core-dryrun
          path: dist/cri-core-dryrun.zip
