name: CI • Smoke (validate → run)
on:
  push:
  pull_request:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Validate & run minimal workflow
        run: |
          python3 cli.py --version || true
          python3 cli.py validate workflows/minimal.json
          python3 cli.py run      workflows/minimal.json
