name: Docs • Guard AWO alignment
on:
  push:
  pull_request:

jobs:
  doc-guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Run doc-guard
        run: |
          python3 tools/doc_guard.py
